### ISSUE TITLE
Document which versions of Grafana are supported

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/grafana#21]
##### SUMMARY

As discussed in 20191216 call, we should document in README which versions of Grafana are supported.

##### ISSUE TYPE
- Documentation Report

**Comment by rrey** [comment]
I have #53 that changes the Readme structure to have the one used on the Kubernetes Collection (I like it).
I also have #54 changing the CI to test on several Grafana versions.

Once both of these PRs are merged I'll update the readme to specify the supported versions.
