### ISSUE TITLE
Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/grafana#66]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of https://github.com/ansible-collection-migration/community.grafana against this repo

##### ISSUE TYPE
- Bug Report

**Comment by gundalow** [comment]
Clarification:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

**Comment by rrey** [comment]
Hi! Do you have any pointer on this last point around collections ?
I’ll try to find time to make the diff on modules and stuff but I’m confident that We are ahead of devel.

**Comment by gundalow** [comment]
Personally I'd check out the two repos then use something like https://meldmerge.org/ to compare the two directories
